<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Thuy" failures="1" tests="8" name="selenium.com.testcases.ImportLogTest" time="205.549" errors="0" timestamp="2024-12-08T14:09:56 ICT" skipped="0">
  <testcase classname="selenium.com.testcases.ImportLogTest" name="testBeginningAmount" time="26.471"/>
  <testcase classname="selenium.com.testcases.ImportLogTest" name="testEndAmount" time="28.668"/>
  <testcase classname="selenium.com.testcases.ImportLogTest" name="testEndQuantity" time="26.895"/>
  <testcase classname="selenium.com.testcases.ImportLogTest" name="checkInventoryBookConsistency" time="26.658">
    <failure message="Có lỗi trong dữ liệu:
Sai sót ở sản phẩm mã 13: , Ngày :08/12/2024, số phiếu nhập : PN24000003 Tồn đầu kỳ = 30, Tồn cuối kỳ trước đó = 50
Sai sót ở sản phẩm mã 12: , Ngày :08/12/2024, số phiếu nhập : PN24000003 Tồn đầu kỳ = 20, Tồn cuối kỳ trước đó = 38
Sai sót ở sản phẩm mã 10: , Ngày :08/12/2024, số phiếu nhập : PN24000004 Tồn đầu kỳ = 50, Tồn cuối kỳ trước đó = 80" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Có lỗi trong dữ liệu:
Sai sót ở sản phẩm mã 13: , Ngày :08/12/2024, số phiếu nhập : PN24000003 Tồn đầu kỳ = 30, Tồn cuối kỳ trước đó = 50
Sai sót ở sản phẩm mã 12: , Ngày :08/12/2024, số phiếu nhập : PN24000003 Tồn đầu kỳ = 20, Tồn cuối kỳ trước đó = 38
Sai sót ở sản phẩm mã 10: , Ngày :08/12/2024, số phiếu nhập : PN24000004 Tồn đầu kỳ = 50, Tồn cuối kỳ trước đó = 80
at org.testng.Assert.fail(Assert.java:111)
at selenium.com.testcases.ImportLogTest.checkInventoryBookConsistency(ImportLogTest.java:80)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- checkInventoryBookConsistency -->
  <testcase classname="selenium.com.testcases.ImportLogTest" name="testStartCalendar" time="23.270"/>
  <testcase classname="selenium.com.testcases.ImportLogTest" name="testEndCalendar" time="23.183"/>
  <testcase classname="selenium.com.testcases.ImportLogTest" name="testFilterByDate" time="24.001"/>
  <testcase classname="selenium.com.testcases.ImportLogTest" name="checkDownloadedExcelFile" time="26.403"/>
</testsuite> <!-- selenium.com.testcases.ImportLogTest -->
